### ISSUE TITLE
[Bug Report] document is not defined - SSR

### ISSUE THREAD

**Issue by DanielAlcaraz** [ElemeFE/element#11761]
### Element UI version
2.4.2

### OS/Browsers version
Windows 10, Chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://github.com/DanielAlcaraz/OnReview](https://github.com/DanielAlcaraz/OnReview)

### Steps to reproduce
npm run dev

When goes to / route this message appears:
     Fatal error when rendering : /
     ReferenceError: document is not defined

### What is Expected?
Load Element Ui without errors.

### What is actually happening?
```
ReferenceError: document is not defined
    at Object.<anonymous> (D:\Projects\OnReview\node_modules\element-ui\lib\utils\dom.js:22:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\OnReview\node_modules\element-ui\lib\utils\popup\popup-manager.js:9:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
Whole request: 158ms
```

**Comment by DanielAlcaraz** [comment]
I create this code in the ```server.js``` to simulate the dom in the server: 
```
const dom = new JSDOM(template)

global.window = dom.window
global.document = window.document
global.navigator = window.navigator
```

Any other solution?

**Comment by Leopoldthecoder** [comment]
Somehow even on the server, your app's `Vue.prototype.$isServer` is still `false` (you can check it by add `console.log(Vue.prototype.$isServer)` on `app.js`).

Make sure `Vue.prototype.$isServer` is `true` when running on server, and things should be fine.
