### ISSUE TITLE
[Bug Report] vue/test-util cannot mount "ElSelectDropdown"

### ISSUE THREAD

**Issue by matthieuHanne** [ElemeFE/element#12634]
### Element UI version
2.4.6

### OS/Browsers version
mac os

### Vue version
2.5.17

### Reproduction Link
[https://github.com/valterbarros/trackthings](https://github.com/valterbarros/trackthings)

### Steps to reproduce
try to mount a component with el-select inside throw :

---> <ElSelectDropdown>
       <Transition>
         <ElSelect>
           <ElFormItem>
             <ElForm>
               <Anonymous>
                 <Root>
TypeError: Cannot read property '$el' of undefined
    at VueComponent.mounted (/Users/mhanne/src/report-builder/viewer/node_modules/element-ui/lib/element-ui.common.js:9131:54)
    at callHook (/Users/mhanne/src/report-builder/viewer/node_modules/vue/dist/vue.runtime.common.js:2919:21)
    at Object.insert (/Users/mhanne/src/report-builder/viewer/node_modules/vue/dist/vue.runtime.common.js:4156:7)
    at invokeInsertHook (/Users/mhanne/src/report-builder/viewer/node_modules/vue/dist/vue.runtime.common.js:5958:28)

### What is Expected?
Mount le select input

### What is actually happening?
test crash. with jest or ava same issues

**Comment by JaekwanLee** [comment]
We face the same issue and tried to find the issue. And I found that the problematic line in ElSelectDropdown is the line it accessing $ref in mounted() as below.
```
mounted() {
...
this.referenceElm = this.$parent.$refs.reference.$el;
...
}
```

The Vue official documents for $ref usage specifies.
> An important note about the ref registration timing: because the refs themselves are created as a result of the render function, you cannot access them on the initial render - they don’t exist yet! $refs is also non-reactive, therefore you should not attempt to use it in templates for data-binding.

As per document, the this.$parent.$refs does not contains child references on mounted. This seems quite clear.

**Comment by matthieuHanne** [comment]
@JaekwanLee Have you find a solution ?

**Comment by JaekwanLee** [comment]
@matthieuHanne Not really. Just testing it with shallowMount for now. It is weird that it seems working when it runs on browser though.

**Comment by GenevievePlantin** [comment]
Hi, is there any development @JaekwanLee ? or @matthieuHanne have found some kind of solution ? I'm currently adding some unit tests with Mocha to my Vue project and I have the same issue.

Thank you :)

**Comment by vladra** [comment]
We've also encountered exactly same issue in tests

**Comment by syn-zeta** [comment]
@ziyoung @wacky6 Any ideas what is to be done here?

**Comment by ziyoung** [comment]
I write a simple demo https://github.com/ziyoung/vue-test-with-jest
All test cases pass.
```
 PASS  src/components/__tests__/hello-world.test.js
 PASS  src/components/Select/__tests__/select.test.js
  ● Console

    console.log src/components/Select/select.vue:18
      HTMLParagraphElement {}
```

**Comment by syn-zeta** [comment]
@ziyoung Here's a patch to your `vue-test-with-jest` that will allow you to reproduce the issue:
 [ref.txt](https://github.com/ElemeFE/element/files/2455352/ref.txt)

**Comment by vladra** [comment]
Also having exactly same issue in tests

**Comment by huihao** [comment]
https://vue-test-utils.vuejs.org/api/components/

`import { config } from '@vue/test-utils'`
`config.stubs.transition = false`

This may solve this problem.

The built-in transition component has property named abstract, but transitionStub does not.

``` 
vue/src/core/instance/lifecycle.js

export function initLifecycle (vm: Component) {
  const options = vm.$opti

  // locate first non-abstract parent
  let parent = options.parent
  if (parent && !options.abstract) {
    while (parent.$options.abstract && parent.$parent) {
      parent = parent.$parent
    }
    parent.$children.push(vm)
  }
 ...
} 
``` 
This causes the child component to have the wrong parent component.

**Comment by kokokele** [comment]
add this 'config.stubs.transition = false;' is ok. 

why?

**Comment by gsccheng** [comment]
Why is the PR https://github.com/ElemeFE/element/pull/13098 closed and not merged?

**Comment by hengkx** [comment]
> Thank you @huihao.
> @matthieuHanne @syn-zeta it should work for you. https://github.com/ziyoung/vue-test-with-jest/blob/master/src/components/__tests__/hello-world.test.js

This is the same mistake.
![image](https://user-images.githubusercontent.com/8358236/48813304-3ae56680-ed71-11e8-8717-f533703d2368.png)

**Comment by psaren** [comment]
@huihao 
Thank you for your solution!

**Comment by yuanalina** [comment]
@huihao Thank you

**Comment by jpenna** [comment]
> We face the same issue and tried to locate the culprit. And I found that the problematic line in ElSelectDropdown is the line it accessing $ref in mounted() as below.
> 
> ```
> mounted() {
> ...
> this.referenceElm = this.$parent.$refs.reference.$el;
> ...
> }
> ```

I couldn't find where this `this.referenceElm` is used. What is this variable for?
I commented it out and both the tests and browser view worked fine.

**Comment by half-shell** [comment]
@ziyoung I would like to ask if this issue could be reopened. I am still having that same exact error, and huihao's answer
```
import { config } from '@vue/test-utils';
config.stubs.transition = false;
```
doesn't solve it. Did anyone find a workaround or a working solution?

**Comment by TheJaredWilcurt** [comment]
Heads up for anyone Googling this in the future, the work around is no longer needed in Vue Test Utils 1.3.1

**Comment by PetersonLian** [comment]
> Heads up for anyone Googling this in the future, the work around is no longer needed in Vue Test Utils 1.3.1

Thanks a thousand times
