### ISSUE TITLE
[Bug Report] element-uilibutilsdom.js:22:39 Reference Error: document is not defined

### ISSUE THREAD

**Issue by hlbj105** [ElemeFE/element#15912]
### Element UI version
0.1.0

### OS/Browsers version
win10/360安全浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
```
$ yarn run dev
yarn run v1.15.2
$ vue-cli-service serve
 INFO  Starting development server...
 10% building 2/2 modules 0 active ERROR  ReferenceError: document is not defined
ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\RuiDe\Desktop\project\hms-admin\node_modules\element-ui\lib\utils\dom.js:22:39)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (C:\Users\RuiDe\Desktop\project\hms-admin\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (C:\Users\RuiDe\Desktop\project\hms-admin\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\RuiDe\Desktop\project\hms-admin\node_modules\element-ui\lib\utils\popup\popup-manager.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (C:\Users\RuiDe\Desktop\project\hms-admin\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (C:\Users\RuiDe\Desktop\project\hms-admin\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is Expected?
非ssr，spa本地开发运行 npm run dev

### What is actually happening?
非ssr，spa本地开发运行 npm run dev

**Comment by qingdengyue** [comment]
没看明白这个啥情况？  是直接运行的element-ui  这个工程，还是你自己建立的工程引入的element-ui?

**Comment by hlbj105** [comment]
@qingdengyue 自己的项目中引入的element-ui，但是看报错定位是在element中，也不知道什么问题

**Comment by luoxinliu** [comment]
@hlbj105 怎么解决的？

**Comment by wivwiv** [comment]
@luoxinliu 
这里面找到了 https://segmentfault.com/q/1010000019383554

**Comment by hlbj105** [comment]
@wivwiv 这个也是我发的🤣

**Comment by wivwiv** [comment]
@hlbj105 看了与 Element 无关，这个只是这个特定的文件被七七八八的引用，其中有一个是 mock 使用的 node 环境

**Comment by hlbj105** [comment]
@wivwiv 
应该是node环境问题，node不能用import ，只能用require

**Comment by luoxinliu** [comment]
@wivwiv 已经解决了，是环境的问题

**Comment by gyfrxy-forever** [comment]
@luoxinliu 您好，这个问题是什么原因导致的，解决了吗

**Comment by luoxinliu** [comment]
> @luoxinliu 您好，这个问题是什么原因导致的，解决了吗

这么久什么原因早忘了，应该是环境问题

**Comment by hlbj105** [comment]
> @luoxinliu 您好，这个问题是什么原因导致的，解决了吗

上面有说原因吧，具体也忘了。
