### ISSUE TITLE
[Bug Report] Documentation at element.eleme.io for table is not displaying examples

### ISSUE THREAD

**Issue by blazejporwol** [ElemeFE/element#16110]
### Element UI version
2.9.1

### OS/Browsers version
Windows, Firefox 67.0.1, IE 11, Chrome 75.0.3770.80

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net

### Steps to reproduce
1. Navigate to https://element.eleme.io/#/en-us/component/table#filter

### What is Expected?
Examples should be displayed below each header ("Filter", "Custom column template" and so on)

### What is actually happening?
No examples are displayed.

In console on each browser there are multiple errors:

Firefox:

TypeError: "n.filter(...)[0] is undefined" 
    langConfig https://element.eleme.io/docs.9555831.js:39
    VueJS 3
    controlText https://element.eleme.io/docs.9555831.js:39
    VueJS 3
    a https://element.eleme.io/docs.9555831.js:39

TypeError: "t.$el.getElementsByClassName is not a function"
    mounted https://element.eleme.io/docs.9555831.js:39
    VueJS 2

Internet Explorer:

"TypeError: Unable to get property 'demo-block' of undefined or null reference
   at r.computed.langConfig (https://element.eleme.io/docs.9555831.js:39:56348)
   at ke.prototype.get (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:16338)
   at ke.prototype.evaluate (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:17486)
   at Anonymous function (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:19384)
   at r.computed.controlText (https://element.eleme.io/docs.9555831.js:39:56634)
   at ke.prototype.get (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:16338)
   at ke.prototype.evaluate (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:17486)
   at Anonymous function (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:19384)
   at Anonymous function (https://element.eleme.io/docs.9555831.js:39:58269)
   at e.prototype._render (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:"

"TypeError: Object doesn't support property or method 'getElementsByClassName'
   at Anonymous function (https://element.eleme.io/docs.9555831.js:39:57972)
   at Anonymous function (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:11629)
   at Bt (https://shadow.elemecdn.com/npm/vue@2.5.21/dist/vue.runtime.min.js:6:11090)"

Chrome:

TypeError: Cannot read property 'demo-block' of undefined
    at a.langConfig (docs.9555831.js:39)
    at ke.get (vue.runtime.min.js:6)
    at ke.evaluate (vue.runtime.min.js:6)
    at a.langConfig (vue.runtime.min.js:6)
    at a.controlText (docs.9555831.js:39)
    at ke.get (vue.runtime.min.js:6)
    at ke.evaluate (vue.runtime.min.js:6)
    at a.controlText (vue.runtime.min.js:6)
    at a.<anonymous> (docs.9555831.js:39)
    at a.e._render (vue.runtime.min.js:6)

TypeError: Cannot read property 'header' of undefined
    at a.langConfig (docs.9555831.js:39)
    at ke.get (vue.runtime.min.js:6)
    at ke.evaluate (vue.runtime.min.js:6)
    at a.langConfig (vue.runtime.min.js:6)
    at a.<anonymous> (docs.9555831.js:39)
    at a.e._render (vue.runtime.min.js:6)
    at a.r (vue.runtime.min.js:6)
    at ke.get (vue.runtime.min.js:6)
    at ke.run (vue.runtime.min.js:6)
    at xe (vue.runtime.min.js:6)

TypeError: t.$el.getElementsByClassName is not a function
    at a.<anonymous> (docs.9555831.js:39)
    at Array.<anonymous> (vue.runtime.min.js:6)
    at Bt (vue.runtime.min.js:6)

Request Timeout
(anonymous) @ docs.9555831.js:39

**Comment by ziyoung** [comment]
`en-US` but not `en-us`
