### ISSUE TITLE
[Bug Report] incorrect dependencies for custom-theme

### ISSUE THREAD

**Issue by attx** [ElemeFE/element#18018]
### Element UI version
2.12.0

### OS/Browsers version
Chrome Version 78.0.3904.87 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://github.com/attx/element-theme

### Steps to reproduce
Go through https://element.eleme.io/#/en-US/component/custom-theme

npm: 6.12.0
node: v12.13.0

1. npm i element-theme -g
2. npm i element-theme-chalk -D
3. et -i
4. error appears (primordials is not defined)

### What is Expected?
no errors

### What is actually happening?
Following error appears:

➜  theme et
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/marcelseliger/.nvm/versions/node/v12.13.0/lib/node_modules/element-theme/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/marcelseliger/.nvm/versions/node/v12.13.0/lib/node_modules/element-theme/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/marcelseliger/.nvm/versions/node/v12.13.0/lib/node_modules/element-theme/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by infjer** [comment]
same problem with you.
I have tried for node v10.x\12.x\13.x，but all failed.

**Comment by infjer** [comment]
downgrade to node v10.x
rm -rf node_modules
npm install

**Comment by edmundmunday** [comment]
Downgrading to an out of date version of node is not an acceptable solution to this issue.
