### ISSUE TITLE
关于el-table-column组件的作用域

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1822]
我做了一个组件，对el-table, el-pagination，列表排序和过滤做了封装。
基本 el-table-column作为slot传入组件。
[代码在这里](https://github.com/njleonzhang/vue-data-tables)

```
<template>
sc-table(:data='tableData',
      :tool-bar-def='toolBarDef',
      :row-action-def='rowActionsDef',
      action-col-width='180',
      :col-not-row-click='["attachments"]',
      @row-click="showDetail")
      el-table-column(prop='flow_no', label='服务编号', sortable='custom')
      el-table-column(prop='flow_type', label='服务类型', sortable='custom')
      el-table-column(prop='attachments', label='附件', inline-template)
        img-viewer(:img-srcs='row.attachments')
</template>

<script>
import ImgViewer from 'components/ImgViewer'

export default {
  components: {
    ImgViewer
  }
}
</script>
```

现在遇到一个问题，就是如果我想在el-table-column里再使用一个自定义组件的话？怎么做才好呢？按我的理解, 设置content为self的话，则作用域是sc-table, 所以应该设置为$parent, 这样作用域里就有ImgViewer了。 

但是并不行，会报这样的错误：

```
    el-table-column(prop='attachments', label='附件', inline-template, context='$parent')
        img-viewer(:img-srcs='row.attachments')
```

```
vue.js?3b81:427 TypeError: Cannot set property 'staticRenderFns' of undefined
    at renderCell (eval at <anonymous> (http://0.0.0.0:8080/app.js:1292:2), <anonymous>:9121:42)
    at Proxy.column.renderCell (eval at <anonymous> (http://0.0.0.0:8080/app.js:1292:2), <anonymous>:9150:11)
    at eval (eval at <anonymous> (http://0.0.0.0:8080/app.js:1292:2), <anonymous>:7640:37)
    at Proxy.renderList (eval at <anonymous> (http://0.0.0.0:8080/app.js:600:2), <anonymous>:3032:18)
    at eval (eval at <anonymous> (http://0.0.0.0:8080/app.js:1292:2), <anonymous>:7628:21)
    at Proxy.renderList (eval at <anonymous> (http://0.0.0.0:8080/app.js:600:2), <anonymous>:3032:18)
    at Proxy.render (eval at <anonymous> (http://0.0.0.0:8080/app.js:1292:2), <anonymous>:7603:16)
    at VueComponent.Vue._render (eval at <anonymous> (http://0.0.0.0:8080/app.js:600:2), <anonymous>:2927:22)
    at VueComponent.eval (eval at <anonymous> (http://0.0.0.0:8080/app.js:600:2), <anonymous>:2335:21)
    at Watcher.get (eval at <anonymous> (http://0.0.0.0:8080/app.js:600:2), <anonymous>:1643:27)
```

请教应该怎么办？

**Comment by QingWei-Li** [comment]
`:context='$parent'`

**Comment by njleonzhang** [comment]
@QingWei-Li 谢谢，很尴尬
