### ISSUE TITLE
不支持ssr服务端渲染吧？

### ISSUE THREAD

**Issue by lin-xi** [ElemeFE/element#1888]
不支持ssr服务端渲染吧？

ReferenceError: window is not defined
    at /Users/linxi/work/javascript/waimai/meeting/node_modules/element-ui/lib/utils/popper.js:51:16
    at root (/Users/linxi/work/javascript/waimai/meeting/node_modules/element-ui/lib/utils/popper.js:42:26)
    at Object.<anonymous> (/Users/linxi/work/javascript/waimai/meeting/node_modules/element-ui/lib/utils/popper.js:47:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/linxi/work/javascript/waimai/meeting/node_modules/element-ui/lib/utils/vue-popper.js:5:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by QingWei-Li** [comment]
这个特性将在 `1.1` 里实现  https://github.com/ElemeFE/element/pull/1867

**Comment by Leopoldthecoder** [comment]
目前不支持。有计划在 1.1 版本中支持：https://github.com/ElemeFE/element/pull/1867
