### ISSUE TITLE
When I run command the console at the wrong time I have no way to continue

### ISSUE THREAD

**Issue by handoing** [ElemeFE/element#22]
➜  element git:(master) ✗ npm run dev

> element-ui@1.0.0-rc.1 dev /Applications/element/element
> npm i && (node bin/iconInit.js & node bin/build-entry.js) && cooking watch -c scripts/cooking.demo.js

npm WARN package.json element-ui@1.0.0-rc.1 No license field.

> element-ui@1.0.0-rc.1 postinstall /Applications/element/element
> lerna bootstrap

Lerna v2.0.0-beta.18
Independent Versioning Mode
Linking all dependencies
Successfully bootstrapped 38 packages.
[build entry] DONE: /Applications/element/element/src/index.js

[cooking] - Failed to read the config.
[cooking] - Error: Cannot find module 'markdown-it'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Applications/element/element/scripts/cooking.demo.js:3:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Applications/element/element/node_modules/cooking/util/load-config.js:18:14)
    at /Applications/element/element/node_modules/cooking/bin/cooking-watch:23:12
    at Array.forEach (native)
    at Object.<anonymous> (/Applications/element/element/node_modules/cooking/bin/cooking-watch:22:16)
    at Module._compile (module.js:409:26)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! element-ui@1.0.0-rc.1 dev: `npm i && (node bin/iconInit.js & node bin/build-entry.js) && cooking watch -c scripts/cooking.demo.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@1.0.0-rc.1 dev script 'npm i && (node bin/iconInit.js & node bin/build-entry.js) && cooking watch -c scripts/cooking.demo.js'.
npm ERR! This is most likely a problem with the element-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && (node bin/iconInit.js & node bin/build-entry.js) && cooking watch -c scripts/cooking.demo.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls element-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/element/element/npm-debug.log

**Comment by QingWei-Li** [comment]
miss `markdown-it` package, i will fix

**Comment by QingWei-Li** [comment]
And you should use NPM 3+

**Comment by QingWei-Li** [comment]
If it still does not work, pls use npm 3.0
