### ISSUE TITLE
[Bug Report] win7无法访问官网

### ISSUE THREAD

**Issue by wameister** [ElemeFE/element#22116]
### Element UI version
2.15.9

### OS/Browsers version
win7

### Vue version
2.7.10

### Reproduction Link
https://elementui.github.io/

### Steps to reproduce
win7打开官网白屏报错 https://element.eleme.io/#/zh-CN
Failed to load resource: net::ERR_CONNECTION_RESET
vue.runtime.min.js:1          Failed to load resource: net::ERR_CONNECTION_RESET
vue-router.min.js:1          Failed to load resource: net::ERR_CONNECTION_RESET
highlight.pack.b1f71b31-3c07-11e9-ba1a-55bba1877129.js:1          Failed to load resource: net::ERR_CONNECTION_RESET
docs.586f45c.js:1 Uncaught ReferenceError: Vue is not defined
    at Object.<anonymous> (docs.586f45c.js:1:11063)
    at B (docs.586f45c.js:1:6870)
    at r (docs.586f45c.js:1:7169)
    at Module.<anonymous> (docs.586f45c.js:1:115187)
    at Module.<anonymous> (docs.586f45c.js:1:116287)
    at B (docs.586f45c.js:1:6870)
    at c (docs.586f45c.js:1:387)
    at docs.586f45c.js:1:10253
    at docs.586f45c.js:1:10257
![Snipaste_2022-08-23_16-57-39](https://user-images.githubusercontent.com/111721782/186118205-da1fcb02-de0e-4ba7-a306-00025b4756c4.png)

### What is Expected?
希望win7可以访问官网

### What is actually happening?
希望win7可以访问官网

**Comment by RSS1102** [comment]
这个应该是浏览器版本的问题？（vue兼容问题）
