### ISSUE TITLE
[Bug Report] 日期时间范围选择控件点击时间选择有报错

### ISSUE THREAD

**Issue by hi500** [ElemeFE/element#22215]
### Element UI version
2.15.10

### OS/Browsers version
Macos Chrome106.0.5249.119

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/hi500/pen/yLELWJG

### Steps to reproduce
https://jsrun.net/QLsKp  详见代码demo   ，日期时间范围选择控件，先点击结束日期，不选择，然后点击开始时间，就报错了
runner.min.js?v=8:211 TypeError: Cannot read properties of null (reading 'getHours')
    at a.hours (element-ui@2.4.8.js:1:287385)

### What is Expected?
不要报错

### What is actually happening?
报错了
runner.min.js?v=8:211 TypeError: Cannot read properties of null (reading 'getHours')
    at a.hours (element-ui@2.4.8.js:1:287385)

**Comment by hi500** [comment]
打开控制台，点击控件，先点击结束日期输入框，然后点击开始时间输入框，就报错了
