### ISSUE TITLE
[Bug Report] npm 打包失败：Cannot use 'in' operator to search for '0' in arguments_marker. File: static/css/chunk-elementUI.68c70ad5.css

### ISSUE THREAD

**Issue by Puppy4C** [ElemeFE/element#22533]
### Element UI version
2.13.2

### OS/Browsers version
Linux

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ziyoung/pen/LKNBqB

### Steps to reproduce
> vue-cli-service build

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

-  Building for production...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 ERROR  Error: CSS minification error: Cannot use 'in' operator to search for '0' in arguments_marker. File: static/css/chunk-elementUI.68c70ad5.css
Error: CSS minification error: Cannot use 'in' operator to search for '0' in arguments_marker. File: static/css/chunk-elementUI.68c70ad5.css
    at /tmp/compile_scm/src/om-server/project/server/sequoiacm-om-omserver/om-ui/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scm-web@1.0.0 build:prod: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scm-web@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/ci/jenkins/.npm/_logs/2023-05-15T19_29_34_018Z-debug.log

### What is Expected?
正常编译

### What is actually happening?
偶现编译失败

**Comment by Puppy4C** [comment]
似乎是：https://github.com/foundation/foundation-sites/issues/10956 ？
