### ISSUE TITLE
el-form 自动验证的prop与vue-devtool 一起用时会报rawGetter is not a function

### ISSUE THREAD

**Issue by Sergisoing** [ElemeFE/element#2522]
```
<el-form :model="ruleForm" :rules="rules" ref="ruleForm" label-width="100px" class="demo-ruleForm">
  <el-form-item label="活动名称" prop="name">
    <el-input v-model="ruleForm.name"></el-input>
  </el-form-item>
  <el-form-item label="活动区域" prop="region">
    <el-select v-model="ruleForm.region" placeholder="请选择活动区域">
      <el-option label="区域一" value="shanghai"></el-option>
      <el-option label="区域二" value="beijing"></el-option>
    </el-select>
  </el-form-item>
  <el-form-item label="活动时间" required>
    <el-col :span="11">
      <el-form-item prop="date1">
        <el-date-picker type="date" placeholder="选择日期" v-model="ruleForm.date1" style="width: 100%;"></el-date-picker>
      </el-form-item>
    </el-col>
    <el-col class="line" :span="2">-</el-col>
    <el-col :span="11">
      <el-form-item prop="date2">
        <el-time-picker type="fixed-time" placeholder="选择时间" v-model="ruleForm.date2" style="width: 100%;"></el-time-picker>
      </el-form-item>
    </el-col>
  </el-form-item>
  <el-form-item label="即时配送" prop="delivery">
    <el-switch on-text="" off-text="" v-model="ruleForm.delivery"></el-switch>
  </el-form-item>
  <el-form-item label="活动性质" prop="type">
    <el-checkbox-group v-model="ruleForm.type">
      <el-checkbox label="美食/餐厅线上活动" name="type"></el-checkbox>
      <el-checkbox label="地推活动" name="type"></el-checkbox>
      <el-checkbox label="线下主题活动" name="type"></el-checkbox>
      <el-checkbox label="单纯品牌曝光" name="type"></el-checkbox>
    </el-checkbox-group>
  </el-form-item>
  <el-form-item label="特殊资源" prop="resource">
    <el-radio-group v-model="ruleForm.resource">
      <el-radio label="线上品牌商赞助"></el-radio>
      <el-radio label="线下场地免费"></el-radio>
    </el-radio-group>
  </el-form-item>
  <el-form-item label="活动形式" prop="desc">
    <el-input type="textarea" v-model="ruleForm.desc"></el-input>
  </el-form-item>
  <el-form-item>
    <el-button type="primary" @click="submitForm('ruleForm')">立即创建</el-button>
    <el-button @click="resetForm('ruleForm')">重置</el-button>
  </el-form-item>
</el-form>
<script>
  export default {
    data() {
      return {
        ruleForm: {
          name: '',
          region: '',
          date1: '',
          date2: '',
          delivery: false,
          type: [],
          resource: '',
          desc: ''
        },
        rules: {
          name: [
            { required: true, message: '请输入活动名称', trigger: 'blur' },
            { min: 3, max: 5, message: '长度在 3 到 5 个字符', trigger: 'blur' }
          ],
          region: [
            { required: true, message: '请选择活动区域', trigger: 'change' }
          ],
          date1: [
            { type: 'date', required: true, message: '请选择日期', trigger: 'change' }
          ],
          date2: [
            { type: 'date', required: true, message: '请选择时间', trigger: 'change' }
          ],
          type: [
            { type: 'array', required: true, message: '请至少选择一个活动性质', trigger: 'change' }
          ],
          resource: [
            { required: true, message: '请选择活动资源', trigger: 'change' }
          ],
          desc: [
            { required: true, message: '请填写活动形式', trigger: 'blur' }
          ]
        }
      };
    },
    methods: {
      submitForm(formName) {
        this.$refs[formName].validate((valid) => {
          if (valid) {
            alert('submit!');
          } else {
            console.log('error submit!!');
            return false;
          }
        });
      },
      resetForm(formName) {
        this.$refs[formName].resetFields();
      }
    }
  }
</script>
```
上面是文档中的自动验证的例子，在本地dev环境跑起来的时候，最开始没有什么问题，当你打开你的devtool，看一些组件信息后，然后刷新reload页面，devtool就会报错
```
TypeError: rawGetter is not a function
    at wrappedGetter (eval at <anonymous> (http://localhost:8089/index.js:1124:2), <anonymous>:703:12)
    at Vue$3.computed.(anonymous function) (eval at <anonymous> (http://localhost:8089/index.js:1124:2), <anonymous>:517:42)
    at Watcher.get (eval at <anonymous> (http://localhost:8089/index.js:650:2), <anonymous>:2934:27)
    at Watcher.evaluate (eval at <anonymous> (http://localhost:8089/index.js:650:2), <anonymous>:3042:21)
    at Vue$3.computedGetter [as default] (eval at <anonymous> (http://localhost:8089/index.js:650:2), <anonymous>:3240:15)
    at Object.get [as default] (eval at <anonymous> (http://localhost:8089/index.js:1124:2), <anonymous>:519:42)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8721)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8751)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8751)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8751)
```
如果把el-form-item中prop属性去掉，就不会报错了，请问这个是什么问题？

**Comment by QingWei-Li** [comment]
vue-devtool 报错你不是应该去 devtool 仓库下提 issue 么

**Comment by lincenying** [comment]
貌似我一直在用devtool, 也没出现过这个问题.
