### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by baqianxin** [ElemeFE/element#284]
#npm run dev error

code
module.js:341
    throw err;
    ^

Error: Cannot find module 'json-templater/string'
  
    at Function.Module._resolveFilename (module.js:339:15)
  
    at Function.Module._load (module.js:290:25)
   
    at Module.require (module.js:367:17)
  
    at require (internal/module.js:16:19)

    at Object.<anonymous> (E:\oom\node-project\element-oom-example\build\bin\build-entry.js:3:14)

    at Module._compile (module.js:413:34)
  
    at Object.Module._extensions..js (module.js:422:10)
 
    at Module.load (module.js:357:32)
 
    at Function.Module._load (module.js:314:12)

    at Function.Module.runMain (module.js:447:10)

#E:\oom\node-project\element-oom-example>npm install json-templater/string -g

    npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get  remote.origin.url

**Comment by baqianxin** [comment]
mint-ui的github项目也出现这样的情况了

**Comment by baqianxin** [comment]
按照makefile 走一遍也没有起来：
`{
  "presets": [["es2015", { "loose": true }]],
  "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]],
  "comments": false
}`
`
ERROR in ./examples/entry.js
Module build failed: ReferenceError: Unknown plugin "xxx" specified in "E:\\oom\\node-project\\element-oom-example\\.babelrc" at 0, attempted to resol
ve relative to "E:\\oom\\node-project\\element-oom-example"
    at C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\file\options\op
tion-manager.js:154:20)
    at OptionManager.mergeOptions (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:228:36)
    at OptionManager.init (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\file\options\option-ma

nager.js:373:12)
    at File.initOptions (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\file\index.js:221:65)
    at new File (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\file\index.js:141:24)
    at Pipeline.transform (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Users\OOM\AppData\Roaming\npm\node_modules\cooking-cli\node_modules\babel-loader\index.js:131:12)
 @ multi app
Child html-webpack-plugin for "index.html":`

**Comment by baqianxin** [comment]
个人觉得问题在.babelrc文件，但是按照列子修改后依然无法运行成功啊

**Comment by reverland** [comment]
要不要清一下缓存

**Comment by baqianxin** [comment]
今天来把昨天剩下的not found module 装的差不多了，感觉曙光就在眼前，但是吧，总觉得不是个办法

**Comment by baqianxin** [comment]
应该是最后一个问题了:
    WARNING in ./examples/route.config.js
11:86 Critical dependency: the request of a dependency is an expression
    const component = page.path === '/changelog' ? require('./pages/changelog.vue') : require(`./docs/zh-cn${page.path}.md`);
![image](https://cloud.githubusercontent.com/assets/6780391/19225829/64920ac6-8ed5-11e6-892f-945aa8b481a4.png)

**Comment by QingWei-Li** [comment]
有正确安装完依赖么，是直接执行的 `npm run dev` 么，我看到你这提示的信息 devDependencies 里该有的你这都提示未找到模块

**Comment by baqianxin** [comment]
好了，我描述一下问题：
`git clone 下来的项目，按照makefile运行，解决所有modul缺省，但是运行还是有问题，
直接download的master运行缺省package,json->dependencies,应该是环境evn问题，
我直接把devdependencies拷贝到dependencies{}下，然后再npm install 再 去 makefile ，一切解决,其实前面有issues描述到这个问题，但没有引起注意
`
![image](https://cloud.githubusercontent.com/assets/6780391/19227347/bc85f44e-8eea-11e6-8ea9-19c13748638d.png)

**Comment by baqianxin** [comment]
### 谢谢各位了！: )
