### ISSUE TITLE
Warning: a promise was rejected with a non-error: [object String]

### ISSUE THREAD

**Issue by zhuowenli** [ElemeFE/element#2923]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 57

### Vue version
2.1.5

### Reproduction Link
https://jsfiddle.net/zhuowenli/kqyf2oL9/

### What is actually happening?

结合 bluebird 使用的时候，点击 MessageBox 确认对话框的取消按钮，控制台会有 `a promise was rejected with a non-error: [object String]` 的警告信息！

```
bluebird@3.4.7:1542 Warning: a promise was rejected with a non-error: [object String]
    at v (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:1838)
    at VueComponent.p.value.p.closeTimer.m.length.p.callback (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:2157)
    at VueComponent.doClose (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:4922)
    at VueComponent.boundFn [as doClose] (https://unpkg.com/vue@2.1.5/dist/vue.js:131:12)
    at VueComponent.handleAction (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:5245)
    at Proxy.boundFn (https://unpkg.com/vue@2.1.5/dist/vue.js:130:14)
    at Object.click [as fn] (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:8569)
From previous event:
    at e (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:2582)
    at Vue$3.b.confirm [as $confirm] (https://unpkg.com/element-ui@1.1.6/lib/index.js:8:3097)
    at Vue$3.handleClickAction (https://fiddle.jshell.net/_display/:50:12)
    at Object.boundFn [as fn] (https://unpkg.com/vue@2.1.5/dist/vue.js:130:14)
    at VueComponent.<anonymous> (https://unpkg.com/vue@2.1.5/dist/vue.js:2750:16)
    at VueComponent.Vue.$emit (https://unpkg.com/vue@2.1.5/dist/vue.js:3254:16)
    at VueComponent.handleClick (https://unpkg.com/element-ui@1.1.6/lib/index.js:3:21043)
    at Object.boundFn [as fn] (https://unpkg.com/vue@2.1.5/dist/vue.js:130:14)
    at HTMLButtonElement.<anonymous> (https://unpkg.com/vue@2.1.5/dist/vue.js:2750:16)
```

**Comment by Leopoldthecoder** [comment]
这个没关系，不影响使用。
