### ISSUE TITLE
Regression 1.2.0: SSR not working anymore

### ISSUE THREAD

**Issue by Atinux** [ElemeFE/element#2976]
Hi there,

Since the version `1.2.0`, the SSR does not work anymore and throw an error:
```bash
ReferenceError: document is not defined
    at addStyle (/app/node_modules/element-ui/lib/element-ui.common.js:24469:23)
    at addStylesToDom (/app/node_modules/element-ui/lib/element-ui.common.js:24432:21)
    at module.exports (/app/node_modules/element-ui/lib/element-ui.common.js:24386:4)
    at Object.<anonymous> (/app/node_modules/element-ui/lib/element-ui.common.js:24244:39)
    at __webpack_require__ (/app/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/app/node_modules/element-ui/lib/element-ui.common.js:24217:2)
    at __webpack_require__ (/app/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/app/node_modules/element-ui/lib/element-ui.common.js:24198:14)
    at __webpack_require__ (/app/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.module.exports.exports.__esModule (/app/node_modules/element-ui/lib/element-ui.common.js:301:21)
```

**Comment by Leopoldthecoder** [comment]
Our mistake. An emergency fix will be released within 24 hours.

**Comment by Leopoldthecoder** [comment]
1.2.1 released.

**Comment by Atinux** [comment]
That was fast, thank you @Leopoldthecoder
