### ISSUE TITLE
el-select multiple ssr bug

### ISSUE THREAD

**Issue by chuangker** [ElemeFE/element#3004]
### ElementUI version
1.2.1

### OS/Browers version
macOS

### Vue version
2.1.8

### Steps to reproduce
基于服务端渲染时，刷新页面后，控制台报错。

经测试发现，当 `el-select` 添加 `multiple` 属性时才会发生。

### What is actually happening?
```
TypeError: Cannot read property '$el' of undefined
    at VueComponent.<anonymous> (/Users/root/Documents/demo/node_modules/element-ui/lib/element-ui.common.js:5469:54)
    at Array.<anonymous> (/Users/root/Documents/demo/node_modules/vue/dist/vue.runtime.common.js:473:20)
    at nextTickHandler (/Users/root/Documents/demo/node_modules/vue/dist/vue.runtime.common.js:422:16)
```

**Comment by Leopoldthecoder** [comment]
能否定位一下报错的语句？

**Comment by chuangker** [comment]
定位到如下文件
```
// element-ui/packages/select/src/select.vue:483
resetInputHeight() {
  this.$nextTick(() => {
    let inputChildNodes = this.$refs.reference.$el.childNodes;
     // ...
  });
}
```

**Comment by Leopoldthecoder** [comment]
麻烦尝试在 `element.common.js` 里的
```javascript
let inputChildNodes = this.$refs.reference.$el.childNodes;
```
前面加上
```javascript
if (!this.$refs.reference) return;
```
看看能否解决问题（当然，请按照 `element.common.js` 里的变量格式写）。

**Comment by chuangker** [comment]
经过最后测试，利用上述代码可以解决该问题。不知这个 bug 什么时候修复及发布？

**Comment by Leopoldthecoder** [comment]
三个工作日以内吧

**Comment by chuangker** [comment]
好的，谢谢！
