### ISSUE TITLE
On demand import element causes build error

### ISSUE THREAD

**Issue by tonypee** [ElemeFE/element#3008]
I have followed the guide to on demand importing the library, and when i add to my webpack.config - i get errors

adding:
```
  "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]]
```

error on build:
```
/Users/tpee/repos/growlabs/portal-fe/node_modules/tapable/lib/Tapable.js:164
		arguments[i].apply(this);
		             ^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/tpee/repos/growlabs/portal-fe/node_modules/tapable/lib/Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (/Users/tpee/repos/growlabs/portal-fe/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/Users/tpee/repos/growlabs/portal-fe/node_modules/webpack/lib/webpack.js:22:48)
    at Object.<anonymous> (/Users/tpee/repos/growlabs/portal-fe/build/dev-server.js:21:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

It seems that webpack doesnt like this format?

### environment

```
<!-- 1.2.1 -->
<!-- macOS/Chrome 53 -->
<!-- 2.1.10 -->
```

**Comment by Leopoldthecoder** [comment]
Looks like this is caused by `tapable` based on the console message.
