### ISSUE TITLE
[Tooltip] SSR issue with the tooltip component

### ISSUE THREAD

**Issue by gahissy** [ElemeFE/element#3050]
### ElementUI version
1.2.1

### OS/Browers version
macOS/Chrome 56

### Vue version
2.1.10

### Steps to reproduce

```
<el-tooltip content="Top center" placement="top">
  <el-button>Dark</el-button>
</el-tooltip>
```

### What is actually happening ?

```
ReferenceError: window is not defined
    at startUpdate (.../node_modules/vue-meta/lib/vue-meta.js:889:116)
    at batchUpdate (.../node_modules/vue-meta/lib/vue-meta.js:903:10)
    at Vue$2.beforeMount (.../node_modules/vue-meta/lib/vue-meta.js:989:17)
    at callHook (.../node_modules/vue/dist/vue.runtime.common.js:2754:19)
    at Vue$2.Vue._mount (.../node_modules/vue/dist/vue.runtime.common.js:2607:5)
    at Vue$2.$mount (.../node_modules/vue/dist/vue.runtime.common.js:6178:15)
    at VueComponent.beforeCreate (.../node_modules/element-ui/lib/element-ui.common.js:14442:9)
    at callHook (.../node_modules/vue/dist/vue.runtime.common.js:2754:19)
    at VueComponent.Vue._init (.../node_modules/vue/dist/vue.runtime.common.js:3377:5)
    at new VueComponent (.../node_modules/vue/dist/vue.runtime.common.js:3500:12)
```

**Comment by QingWei-Li** [comment]
IThis bug is caused by vue-meta.

```js
// fallback to timers if rAF not present
var stopUpdate = (typeof window !== 'undefined' ? window.cancelAnimationFrame : null) || clearTimeout;
var startUpdate = (typeof window !== 'undefined' ? window.requestAnimationFrame : null) || (function (cb) { return window.setTimeout(cb, 0); });
```

`window.setTimeout`
