### ISSUE TITLE
[Bug Report] Vue   Element-UI   Meteor gives the following error: "import Vue from 'vue'; ... SyntaxError: Unexpected reserved word"

### ISSUE THREAD

**Issue by gczh** [ElemeFE/element#5391]
### Element UI version
1.3.6

### OS/Browsers version
macOS Sierra Version 10.12 / Google Chrome Version 59.0.3071.86 (Official Build) (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://github.com/gczh/meteor-vue2-example](https://github.com/gczh/meteor-vue2-example)

### Steps to reproduce
Run the following commands in the given sequence:
```bash
meteor npm i
meteor
```

Note: try doing the following

```bash
npm uninstall -S element-ui
meteor
```

You should be able to get meteor working again.

I believe that some element-ui dependency is causing a conflict with vue and or meteor. I'm not quite sure which it's conflicting with though.

### What is Expected?
```bash
$ meteor
=> Started proxy.
   [HMR] Dev server listening on port 3003
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

### What is actually happening?
We get the following error:

```bash
W20170615-15:55:06.801(8)? (STDERR) /Users/SOHAPPY/Documents/Projects/meteor-vue2-example/.meteor/local/build/programs/server/packages/modules.js:936
W20170615-15:55:06.804(8)? (STDERR) import Vue from 'vue';
W20170615-15:55:06.806(8)? (STDERR) ^^^^^^
W20170615-15:55:06.807(8)? (STDERR)
W20170615-15:55:06.807(8)? (STDERR) SyntaxError: Unexpected reserved word
W20170615-15:55:06.808(8)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170615-15:55:06.810(8)? (STDERR)     at /Users/SOHAPPY/Documents/Projects/meteor-vue2-example/.meteor/local/build/programs/server/boot.js:331:30
W20170615-15:55:06.814(8)? (STDERR)     at Array.forEach (native)
W20170615-15:55:06.816(8)? (STDERR)     at Function._.each._.forEach (/Users/SOHAPPY/.meteor/packages/meteor-tool/.1.5.0.1krbjsg  os.osx.x86_64 web.browser web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170615-15:55:06.817(8)? (STDERR)     at /Users/SOHAPPY/Documents/Projects/meteor-vue2-example/.meteor/local/build/programs/server/boot.js:158:5
W20170615-15:55:06.819(8)? (STDERR)     at /Users/SOHAPPY/Documents/Projects/meteor-vue2-example/.meteor/local/build/programs/server/boot.js:387:5
W20170615-15:55:06.820(8)? (STDERR)     at Function.run (/Users/SOHAPPY/Documents/Projects/meteor-vue2-example/.meteor/local/build/programs/server/profile.js:510:12)
W20170615-15:55:06.822(8)? (STDERR)     at /Users/SOHAPPY/Documents/Projects/meteor-vue2-example/.meteor/local/build/programs/server/boot.js:386:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
^C
```

**Comment by gczh** [comment]
Referencing https://github.com/meteor/meteor-feature-requests/issues/6, it could be that element-ui is not transpiled into ES2015 syntax. As meteor doesn't seem to transpile node_modules, this could be why it's breaking things.
