### ISSUE TITLE
配置如下报错 Error when rendering component 

### ISSUE THREAD

**Issue by bigrocs** [ElemeFE/element#558]
##报错如下
`
[Vue warn]: Error when rendering component <ElButton>: warn @ vue.js?ea6b:2611Vue._render @ vue.js?ea6b:2243(anonymous function) @ vue.js?ea6b:1695get @ vue.js?ea6b:740Watcher @ vue.js?ea6b:732Vue._mount @ vue.js?ea6b:1694Vue$3.$mount @ vue.js?ea6b:5592Vue$3.$mount @ vue.js?ea6b:7494init @ vue.js?ea6b:1978createElm @ vue.js?ea6b:3825createChildren @ vue.js?ea6b:3871createElm @ vue.js?ea6b:3856patch @ vue.js?ea6b:4204Vue._update @ vue.js?ea6b:1720(anonymous function) @ vue.js?ea6b:1695get @ vue.js?ea6b:740Watcher @ vue.js?ea6b:732Vue._mount @ vue.js?ea6b:1694Vue$3.$mount @ vue.js?ea6b:5592Vue$3.$mount @ vue.js?ea6b:7494init @ vue.js?ea6b:1978createElm @ vue.js?ea6b:3825patch @ vue.js?ea6b:4239Vue._update @ vue.js?ea6b:1720(anonymous function) @ vue.js?ea6b:1695get @ vue.js?ea6b:740Watcher @ vue.js?ea6b:732Vue._mount @ vue.js?ea6b:1694Vue$3.$mount @ vue.js?ea6b:5592Vue$3.$mount @ vue.js?ea6b:7494initRender @ vue.js?ea6b:2208Vue._init @ vue.js?ea6b:2552Vue$3 @ vue.js?ea6b:2594(anonymous function) @ app.js?8b67:269 @ app.js:87__webpack_require__ @ app.js:200 @ app.js:64(anonymous function) @ app.js:67
3vue.js?ea6b:2252 Uncaught ReferenceError: _slotContents is not defined
`
app.js文件如下
`import Vue from 'vue'
import Element from 'element-ui'
import 'element-ui/lib/theme-default/index.css'

Vue.use(Element)

var Main = {
  template: ”

      <div>
          <el-button>默认按钮</el-button>
          <el-button type="primary">主要按钮</el-button>
          <el-button type="text">文字按钮</el-button>
        </div>
  “
}

const app = new Vue({
    el: '#app',
    render: h => h(Main)
});`
 
package.json
文件如下
`{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "css-loader": "^0.25.0",
    "element-ui": "^0.2.6",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-11",
    "laravel-elixir-browsersync-official": "^1.0.0",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.16.2",
    "style-loader": "^0.13.1",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.1"
  }
}
`

**Comment by QingWei-Li** [comment]
element-ui 最新版是 1.0.0-rc.7
```
npm i element-ui@next -S
```

**Comment by bigrocs** [comment]
更换"element-ui": "^1.0.0-rc.7" 编译出现下面错误``
`[Error: ./~/.1.0.0-rc.7@element-ui/lib/element-ui.common.js
Module build failed: SyntaxError: 'with' in strict mode (1940:36)
    at Parser.pp$4.raise (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:2221:15)
    at Parser.pp$1.parseWithStatement (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:932:27)
    at Parser.pp$1.parseStatement (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:708:32)
    at Parser.pp$1.parseBlock (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:2105:24)
    at Parser.pp$1.parseFunction (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:1810:19)
    at Parser.parseExprAtom (D:\phpStudy\WWW\laravelvue\node_modules\.0.12.5@buble\dist\buble.umd.js:656:26)
    at Parser.pp$3.parseExprSubscripts (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (D:\phpStudy\WWW\laravelvue\node_modules\.3.3.0@acorn\dist\acorn.js:1692:19)
 @ ./resources/assets/js/app.js 2:0-32]`

**Comment by QingWei-Li** [comment]
官方框架配置有 bug
参考 https://github.com/ElementUI/element-in-laravel-starter

这一行 https://github.com/ElementUI/element-in-laravel-starter/blob/80e876282ed78555a4c30060982aa9bc6aa61fac/gulpfile.js#L17

**Comment by bigrocs** [comment]
谢谢

**Comment by bigrocs** [comment]
谢谢成功了  Elixir.webpack.config.module.loaders = [];
