### ISSUE TITLE
使用babel-plugin-component的方式引入组件的问题

### ISSUE THREAD

**Issue by yanguanyu** [ElemeFE/element#58]
代码在：https://github.com/yanguanyu/vue-element-demo
环境：windows10 ,  nodejs v6.5.0 , npm 3.10.3
问题
* 1、编译报错,Cannot read property '0' of null，需要修改babel-plugin-component的源码core.js，把importMethod方法中的file.addImport('xxx'); 改成 file.addImport('xxx', 'default');
 就可以正常编译使用。
是我哪里配置有问题吗？比如babel版本不对？
* 2、上面的问题解决完后，使用babel-plugin-component的方式引入了Table和TableColumn，但是TableColumn没有对应的css，导致导入报错，编译无法进行。需要手动添加一个空的table-column.css文件才能继续使用。
针对这种情况你们如何处理？
谢谢！

错误log
for 1
ERROR in ./src/main.js                                                                                                                                                                             
Module build failed: TypeError: e:/gitRepo/vue-demo/src/main.js: Cannot read property '0' of null                                                                                                  
    at Buffer._append (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\buffer.js:78:25)                                                                                                       
    at Buffer.append (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\buffer.js:55:10)                                                                                                        
    at Generator._append (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\printer.js:206:52)                                                                                                  
    at Generator.word (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\printer.js:131:10)                                                                                                     
    at Generator.Identifier (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\generators\types.js:39:8)                                                                                        
    at e:\gitRepo\vue-demo\node_modules\babel-generator\lib\printer.js:295:23                                                                                                                      
    at Buffer.withSource (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\buffer.js:151:5)                                                                                                    
    at Generator.withSource (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\printer.js:189:15)                                                                                               
    at Generator.print (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\printer.js:294:10)                                                                                                    
    at Generator.ImportSpecifier (e:\gitRepo\vue-demo\node_modules\babel-generator\lib\generators\modules.js:22:8)                                                                                 
 @ multi main

for 2
ERROR in ./src/main.js                                                                                                                                                                             
Module not found: Error: Can't resolve 'element-ui/lib/theme-default/table-column.css' in 'e:\gitRepo\vue-demo\src'                                                                                
 @ ./src/main.js 1:0-70                                                                                                                                                                            
 @ multi main

**Comment by QingWei-Li** [comment]
第一个问题: 我把 babelrc 的 es2015 配置里的 modules 去掉，也就用 babel 处理 modules，是正常的。当初并没有考虑到用 webpack 2 的情况，我研究下怎么修复。

第二个问题: 少了样式文件，我们这边补上。

**Comment by yanguanyu** [comment]
ok  thx

**Comment by QingWei-Li** [comment]
fixed in https://github.com/QingWei-Li/babel-plugin-component/commit/c734a4fcc3414488af5e9d2736688c6cd6d57fef

升级到 0.4.1
