### ISSUE TITLE
[Bug Report] Build error

### ISSUE THREAD

**Issue by lllito** [ElemeFE/element#6406]
### Element UI version
1.4.2

### OS/Browsers version
mac

### Vue version
2.4.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
1

### What is Expected?
build success

### What is actually happening?
The following error occurred during build
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle element-starter@~prebuild: element-starter@
6 silly lifecycle element-starter@~prebuild: no script for prebuild, continuing
7 info lifecycle element-starter@~build: element-starter@
8 verbose lifecycle element-starter@~build: unsafe-perm in lifecycle true
9 verbose lifecycle element-starter@~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/lito/Documents/Lito/mpms2frontend/node_modules/.bin:/Applications/MAMP/bin/php/php7.1.1/bin:/Users/lito/.rvm/gems/ruby-2.2.2/bin:/Users/lito/.rvm/gems/ruby-2.2.2@global/bin:/Users/lito/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lito/.rvm/bin
10 verbose lifecycle element-starter@~build: CWD: /Users/lito/Documents/Lito/mpms2frontend
11 silly lifecycle element-starter@~build: Args: [ '-c', 'rimraf dist && webpack -p --progress --hide-modules' ]
12 silly lifecycle element-starter@~build: Returned: code: 2  signal: null
13 info lifecycle element-starter@~build: Failed to exec build script
14 verbose stack Error: element-starter@ build: `rimraf dist && webpack -p --progress --hide-modules`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid element-starter@
16 verbose cwd /Users/lito/Documents/Lito/mpms2frontend
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error element-starter@ build: `rimraf dist && webpack -p --progress --hide-modules`
22 error Exit status 2
23 error Failed at the element-starter@ build script 'rimraf dist && webpack -p --progress --hide-modules'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the element-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rimraf dist && webpack -p --progress --hide-modules
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs element-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls element-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
PACKAGE.JSON 
```
{
  "name": "element-starter",
  "description": "A Vue.js project",
  "author": "yi.shyang@ele.me",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --hot --env.dev",
    "build": "rimraf dist && webpack -p --progress --hide-modules"

  },
  "dependencies": {
    "element-ui": "^1.1.2",
    "js-md5": "^0.6.0",
    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "moment": "^2.18.1",
    "throttle-debounce": "^1.0.1",
    "vue": "^2.1.8",
    "vue-carousel": "^0.6.4",
    "vue-easy-slider": "^3.1.1",
    "vue-qart": "^2.0.7",
    "vuex": "^2.3.1"
  },
  "engines": {
    "node": ">=6"
  },
  "devDependencies": {
    "autoprefixer": "^6.6.0",
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.0",
    "babel-preset-vue-app": "^1.2.0",
    "css-loader": "^0.27.0",
    "file-loader": "^0.10.1",
    "html-webpack-plugin": "^2.24.1",
    "postcss-loader": "^1.3.3",
    "rimraf": "^2.5.4",
    "style-loader": "^0.13.2",
    "url-loader": "^0.5.8",
    "vue-loader": "^11.1.4",
    "vue-template-compiler": "^2.1.8",
    "vuex": "^2.3.1",
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.2"
  }
}
```
webpack.config.js
```
const resolve = require('path').resolve
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const url = require('url')
const publicPath = ''

module.exports = (options = {}) => ({
  entry: {
    vendor: './src/vendor',
    index: './src/main.js'
  },
  output: {
    path: resolve(__dirname, 'dist'),
    filename: options.dev ? '[name].js' : '[name].js?[chunkhash]',
    chunkFilename: '[id].js?[chunkhash]',
    publicPath: options.dev ? '/assets/' : publicPath
  },
  module: {
    rules: [{
        test: /\.vue$/,
        use: ['vue-loader']
      },
      {
        test: /\.js$/,
        use: ['babel-loader'],
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader','postcss-loader']
      },
      {
        test: /\.less$/,
        loader: "style-loader!css-loader!less-loader",
      },
      {
        test: /\.(png|jpg|jpeg|gif|eot|ttf|woff|woff2|svg|svgz)(\?.+)?$/,
        use: [{
          loader: 'url-loader',
          options: {
            limit: 10000
          }
        }]
      }
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
    new HtmlWebpackPlugin({
      template: 'src/index.html'
    })
  ],
  resolve: {
    alias: {
      '~': resolve(__dirname, 'src')
    }
  },
  devServer: {
    host: '127.0.0.1',
    port: 8010,
    proxy: {
      '/api/': {
        target: 'http://127.0.0.1:8080',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    },
    historyApiFallback: {
      index: url.parse(options.dev ? '/assets/' : publicPath).pathname
    }
  },
  devtool: options.dev ? '#eval-source-map' : '#source-map'
})

```

**Comment by Leopoldthecoder** [comment]
I cloned the repo and ran `npm run build` successfully. Make sure you have all dependencies installed correctly, and your `node` and `npm` are the latest.
