### ISSUE TITLE
求助: clone 庫后npm run dev報錯

### ISSUE THREAD

**Issue by cnweibo** [ElemeFE/element#643]
求助啊，npm run dev出錯啦，看了其他人的方案，我一直沒有搞定：
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.6
3 info using node@v4.4.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle element-ui@1.0.0-rc.7~predev: element-ui@1.0.0-rc.7
6 silly lifecycle element-ui@1.0.0-rc.7~predev: no script for predev, continuing
7 info lifecycle element-ui@1.0.0-rc.7~dev: element-ui@1.0.0-rc.7
8 verbose lifecycle element-ui@1.0.0-rc.7~dev: unsafe-perm in lifecycle true
9 verbose lifecycle element-ui@1.0.0-rc.7~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Administrator\devenvironment\Code\element\node_modules\.bin;C:\Users\Administrator\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\wamp64\bin\php\php5.6.16;C:\wamp64\bin\mysql\mysql5.7.9\bin>;C:\Python27;C:\Program Files\nodejs;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle element-ui@1.0.0-rc.7~dev: CWD: C:\Users\Administrator\devenvironment\Code\element
11 silly lifecycle element-ui@1.0.0-rc.7~dev: Args: [ '/d /s /c',
11 silly lifecycle   'npm install && npm run build:file && cooking watch -c build/cooking.demo.js -p' ]
12 silly lifecycle element-ui@1.0.0-rc.7~dev: Returned: code: 1  signal: null
13 info lifecycle element-ui@1.0.0-rc.7~dev: Failed to exec dev script
14 verbose stack Error: element-ui@1.0.0-rc.7 dev: `npm install && npm run build:file && cooking watch -c build/cooking.demo.js -p`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid element-ui@1.0.0-rc.7
16 verbose cwd C:\Users\Administrator\devenvironment\Code\element
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v4.4.7
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error element-ui@1.0.0-rc.7 dev: `npm install && npm run build:file && cooking watch -c build/cooking.demo.js -p`
22 error Exit status 1
23 error Failed at the element-ui@1.0.0-rc.7 dev script 'npm install && npm run build:file && cooking watch -c build/cooking.demo.js -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the element-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && npm run build:file && cooking watch -c build/cooking.demo.js -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs element-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls element-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by cnweibo** [comment]
已经找到原因，是因为未安装windows下的编译工具所导致 https://github.com/nodejs/node-gyp 可以参考
