### ISSUE TITLE
更新为1.0.0-rc.8后，发现如下的报错信息

### ISSUE THREAD

**Issue by amin168** [ElemeFE/element#720]
我是点击导航栏快速切换页面时（配合vue-router）使用，就出现下面的报错信息了，之前的版本都没出现，不知道是我的问题，还是怎么样的

这个图是报documentHandler的错
![123](https://cloud.githubusercontent.com/assets/10808093/19829482/7b29bdc0-9e15-11e6-8682-b476088ece68.png)

这个图是报Cannot read property 'id' of undefined
![124](https://cloud.githubusercontent.com/assets/10808093/19829490/be74798a-9e15-11e6-962c-457705cf5072.png)

![1245](https://cloud.githubusercontent.com/assets/10808093/19829495/ed35cae4-9e15-11e6-9d11-70d0332b0878.png)

clickoutside.js:12 Uncaught TypeError: Cannot read property 'documentHandler' of undefined
    at http://localhost:33506/dist/main.js:22403:22
    at Array.forEach (native)
    at HTMLDocument.<anonymous> (http://localhost:33506/dist/main.js:22402:13)(anonymous function) @ clickoutside.js:12(anonymous function) @ clickoutside.js:11
clickoutside.js:50 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at unbind (http://localhost:33506/dist/main.js:22441:28)
    at callHook$1 (http://localhost:33506/dist/vendors.js:4488:6)
    at updateDirectives (http://localhost:33506/dist/vendors.js:4453:10)
    at Array.unbindDirectives (http://localhost:33506/dist/vendors.js:4390:6)
    at invokeDestroyHook (http://localhost:33506/dist/vendors.js:4057:65)
    at VueComponent.patch [as __patch__] (http://localhost:33506/dist/vendors.js:4311:24)
    at VueComponent.Vue.$destroy (http://localhost:33506/dist/vendors.js:1940:9)
    at destroy$1 (http://localhost:33506/dist/vendors.js:2128:20)
    at invokeDestroyHook (http://localhost:33506/dist/vendors.js:4056:60)
    at invokeDestroyHook (http://localhost:33506/dist/vendors.js:4061:10)

**Comment by QingWei-Li** [comment]
你有手动移除元素么，给个 demo 吧

**Comment by perfectyang** [comment]
![image](https://cloud.githubusercontent.com/assets/8724828/19834012/7b4c7422-9e89-11e6-9998-bde89514a5e0.png)
我也会出现同样问题，主要是页面里的元素有，增删时

**Comment by amin168** [comment]
@perfectyang 你现在有解决方案吗

**Comment by perfectyang** [comment]
暂时没有

**Comment by QingWei-Li** [comment]
我这没法复现，按照你们说半天只提供的“页面元素有增删”的描述，我试验了没报错

**Comment by perfectyang** [comment]
@QingWei-Li 能加一下你的Ｑ,我本地远程，你操作一下吗

**Comment by perfectyang** [comment]
我的Ｑ2406790623

**Comment by QingWei-Li** [comment]
写个 demo 吧麻烦，我不用 Q

**Comment by amin168** [comment]
@QingWei-Li  已提交demo，主要可能是因为分页组件引起的，你多次切换路由，然后看看console控制的报错信息
https://github.com/amin168/element-720

**Comment by erwinQiu** [comment]
@csvwolf 我升级到1.0.0-rc.9 问题依然存在，我发现rc.9没有包涵你的commit。

**Comment by guyuesha** [comment]
同遇到该问题，http://element.eleme.io/#/component/form组件例子中动态增减表单项内，多添加删除几次域名就会发现不会alert提交。

**Comment by QingWei-Li** [comment]
@guyuesha 测试了并没有出现你的问题，而且[动态增加表单项](http://element.eleme.io/#/component/form#dong-tai-zeng-jian-biao-dan-xiang)那里并没有 clickoutside 吧？

**Comment by guyuesha** [comment]
1》邮箱输入：123@126.com 点击提交
2》删除第一个域名，点击提交
3》再输入所有域名，点击提交发现已无效果不会alert

**Comment by QingWei-Li** [comment]
@guyuesha 不是这个 issue 导致的，建议你重新开一个 issue 谢谢
