### ISSUE TITLE
数据从 vuex 中获取的时候，el-table组件报错

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#731]
> 这个错误只有在 rc.8才会出现，是这个版本改动引起的吗

### ElementUI version

1.0.0-rc.8
### Vue version

2.0.3
### Vuex version

2.0.0
### Error info

``` javascript
vue.js?3de6:2611 [Vue warn]: Error in watcher "state" 
(found in root instance)warn @ vue.js?3de6:2611run @ vue.js?3de6:825update @ vue.js?3de6:797notify @ vue.js?3de6:564set @ vue.js?3de6:1159(anonymous function) @ index.js?c168:4setData @ index.js?c168:4d.commit @ index.js?c168:4handler @ index.js?c168:4run @ vue.js?3de6:823flushSchedulerQueue @ vue.js?3de6:627nextTickHandler @ vue.js?3de6:405
vue.js?3de6:2611 [Vue warn]: Error in watcher "data" 
(found in component <el-table>)warn @ vue.js?3de6:2611run @ vue.js?3de6:825flushSchedulerQueue @ vue.js?3de6:627nextTickHandler @ vue.js?3de6:405
```

``` javascript
vue.js?3de6:2611 [Vue warn]: Error in watcher "data" 
(found in component <el-table>)warn @ vue.js?3de6:2611run @ vue.js?3de6:825flushSchedulerQueue @ vue.js?3de6:627nextTickHandler @ vue.js?3de6:405
vuex.js?90cb:145 Uncaught (in promise) Error: [vuex] Do not mutate vuex store state outside mutation handlers.
    at assert (eval at ./node_modules/vuex/dist/vuex.js (http://localhost:9999/vendor.js:418:1), <anonymous>:145:27)
    at Vue$3.store._vm.$watch.deep (eval at ./node_modules/vuex/dist/vuex.js (http://localhost:9999/vendor.js:418:1), <anonymous>:491:5)
    at Watcher.run (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:823:19)
    at Watcher.update (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:797:10)
    at Dep.notify (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:564:13)
    at Function.set (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:1159:10)
    at eval (eval at ./node_modules/element-ui/lib/index.js (http://localhost:9999/vendor.js:347:1), <anonymous>:4:13540)
    at Array.forEach (native)
    at d.setData (eval at ./node_modules/element-ui/lib/index.js (http://localhost:9999/vendor.js:347:1), <anonymous>:4:13503)
    at d.commit (eval at ./node_modules/element-ui/lib/index.js (http://localhost:9999/vendor.js:347:1), <anonymous>:4:16815)assert @ vuex.js?90cb:145store._vm.$watch.deep @ vuex.js?90cb:491run @ vue.js?3de6:823update @ vue.js?3de6:797notify @ vue.js?3de6:564set @ vue.js?3de6:1159(anonymous function) @ index.js?c168:4setData @ index.js?c168:4d.commit @ index.js?c168:4handler @ index.js?c168:4run @ vue.js?3de6:823flushSchedulerQueue @ vue.js?3de6:627nextTickHandler @ vue.js?3de6:405
```

``` javascript
vuex.js?90cb:145 Uncaught (in promise) Error: [vuex] Do not mutate vuex store state outside mutation handlers.
    at assert (eval at ./node_modules/vuex/dist/vuex.js (http://localhost:9999/vendor.js:418:1), <anonymous>:145:27)
    at Vue$3.store._vm.$watch.deep (eval at ./node_modules/vuex/dist/vuex.js (http://localhost:9999/vendor.js:418:1), <anonymous>:491:5)
    at Watcher.run (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:823:19)
    at Watcher.update (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:797:10)
    at Dep.notify (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:564:13)
    at Function.set (eval at ./node_modules/vue/dist/vue.js (http://localhost:9999/vendor.js:404:1), <anonymous>:1159:10)
    at eval (eval at ./node_modules/element-ui/lib/index.js (http://localhost:9999/vendor.js:347:1), <anonymous>:4:13540)
    at Array.forEach (native)
    at d.setData (eval at ./node_modules/element-ui/lib/index.js (http://localhost:9999/vendor.js:347:1), <anonymous>:4:13503)
    at d.commit (eval at ./node_modules/element-ui/lib/index.js (http://localhost:9999/vendor.js:347:1), <anonymous>:4:16815)assert @ vuex.js?90cb:145store._vm.$watch.deep @ vuex.js?90cb:491run @ vue.js?3de6:823update @ vue.js?3de6:797notify @ vue.js?3de6:564set @ vue.js?3de6:1159(anonymous function) @ index.js?c168:4setData @ index.js?c168:4d.commit @ index.js?c168:4handler @ index.js?c168:4run @ vue.js?3de6:823flushSchedulerQueue @ vue.js?3de6:627nextTickHandler @ vue.js?3de6:405
```

![image](https://cloud.githubusercontent.com/assets/10893176/19836556/63bc598e-9edf-11e6-957d-e4351076f7a1.png)

**Comment by furybean** [comment]
这个版本的 table 改动是比较大，看起来你是用了 vuex，是在所有用 vuex 的场景下都会报错么？还是某些场景下。

**Comment by isunkui** [comment]
在所有的 table 场景下都会出错，只升级了 element-ui 这个库，代码和其他都没改动，数据都是从 vuex 获取的，data 的初始值都是 `[]`，需要我这边提供 demo 吗? @furybean

**Comment by QingWei-Li** [comment]
因为现在 table 会对操作原数据，所以涉及到单项绑定的地方都会出错

**Comment by furybean** [comment]
@isunkui 我写了个简单的例子试了试，没办法重现。也找了另外两个同事试了试，也是没办法重现。可能还需要点其他的条件才会触发这个问题，所以需要你提供一个例子。

**Comment by linhaobin** [comment]
遇到同样问题！！

**Comment by csvwolf** [comment]
@linhaobin 可以提供一个demo吗？我这里也用了vuex并没有发现这个问题。

**Comment by isunkui** [comment]
@furybean @csvwolf [https://github.com/isunkui/element-table-demo](https://github.com/isunkui/element-table-demo)

**Comment by isunkui** [comment]
关闭 vuex 的严格模式，就不会有这个错误了

**Comment by furybean** [comment]
#800 里面修了这个问题。
