### ISSUE TITLE
dist 报错

### ISSUE THREAD

**Issue by magang0425** [ElemeFE/element#8]
Error: Cannot find module 'cooking/util/check'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\caiban\.cooking\node_modules\slush-cooking-v
ue\slushfile.js:8:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by QingWei-Li** [comment]
删除 `~/.cooking` 目录重新安装下插件，手误发了新版本

**Comment by magang0425** [comment]
删除.cooking 目录后重装 window 下还是报错 

 |     | `-- ansi-regex@2.0.0
  |     +-- strip-ansi@3.0.1
  |     `-- supports-color@2.0.0
  `-- vue-style-loader@1.0.0

[cooking] - 安装成功

[cooking] - Failed to read the config.
[cooking] - Error: Cannot find module 'cooking/util/check'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\caiban\.cooking\node_modules\cooking-vue\css-loader.js:2:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\caiban\.cooking\node_modules\cooking-vue\index.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)


npm ERR! Windows_NT 10.0.10586
npm ERR! argv "E:\\dev\\nodejs\\node.exe" "E:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! element-ui@1.0.0-rc.1 dist: `rm -rf lib && cooking build -c scripts/cooking.conf.js -p && cooking build -c scripts/cooking.component.js -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@1.0.0-rc.1 dist script 'rm -rf lib && cooking build -c scripts/cooking.conf.js -p && cooking build -c scripts/cooking.component.js -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the element-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf lib && cooking build -c scripts/cooking.conf.js -p && cooking build -c scripts/cooking.component.js -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls element-ui
npm ERR! There is likely additional logging output above.

**Comment by QingWei-Li** [comment]
cooking-vue 是 0.5.0 的么？我七小时前发的，我刚才安装了测试是可以的

可以通过 `cooking list` 看已安装插件的版本号

**Comment by magang0425** [comment]
cooking remove vue
cooking import vue

执行之后还是0.4.3 版本

**Comment by QingWei-Li** [comment]
奇怪
那你到 `C:\Users\caiban.cooking` 目录下手动 'npm un cooking-vue -S && npm i cooking-vue -S' 把

**Comment by magang0425** [comment]
可以了，谢谢
