### ISSUE TITLE
element在vue-cli生成的webpack项目中丢失css效果

### ISSUE THREAD

**Issue by iedwin** [ElemeFE/element#81]
vue-cli生成项目后，npm install --save element-ui@next加入项目。App.vue中只是加入template想看看效果，却发现button等控件都没有bootstrap css效果：
```
<template>
  <div id="app">
    <div class="block">
  <span class="demonstration">默认显示颜色</span>
  <span class="wrapper">
    <el-button type="success">成功按钮</el-button>
    <el-button type="warning">警告按钮</el-button>
    <el-button type="danger">危险按钮</el-button>
    <el-button type="info">信息按钮</el-button>
  </span>
</div>
<div class="block">
  <span class="demonstration">hover 显示颜色</span>
  <span class="wrapper">
    <el-button :plain="true" type="success">成功按钮</el-button>
    <el-button :plain="true" type="warning">警告按钮</el-button>
    <el-button :plain="true" type="danger">危险按钮</el-button>
    <el-button :plain="true" type="info">信息按钮</el-button>
  </span>
</div>
  </div>
  </template>
```

**Comment by jikkai** [comment]
有没有把样式文件'element-ui/lib/theme-default/index.css' import进来？

**Comment by iedwin** [comment]
确实没有加进来，直接在index.html中引入吗？

**Comment by jikkai** [comment]
请参考quick-start：
https://github.com/ElemeFE/element#quick-start

**Comment by iedwin** [comment]
##### 按照quick-start配置了还是不行啊。
##### main.js:
```
import Vue from 'vue'
import App from './App.vue'
import Element from 'element-ui'
import 'element-ui/lib/theme-default/index.css'

Vue.use(Element)


new Vue({
  el: '#app',
  render: h => h(App)
})
```

##### .babelrc
```
{
  "plugins": ["xxx", ["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]]
}
```

##### Error：
```
ERROR in ./src/main.js
Module build failed: ReferenceError: Unknown plugin "xxx" specified in "/Users/fan/Code/Centling/Vue/edwin-hehe-2/.babelrc" at 0, attempted to resolve relative to "/Users/fan/Code/Centling/Vue/edwin-hehe-2"
    at /Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/fan/Code/Centling/Vue/edwin-hehe-2/node_modules/babel-loader/index.js:131:12)
 @ multi main
```

**Comment by Leopoldthecoder** [comment]
如果不使用 `babel-plugin-component` 的话，不需要在 .babelrc 里做任何改动，你的 main.js 里有 `import 'element-ui/lib/theme-default/index.css'` 就可以了。
如果使用 `babel-plugin-component`，首先需要 `npm i babel-plugin-component -S`，其次 .babelrc 里的 `xxx` 代表的是其他插件，而不是一个 'xxx' 字面量。

**Comment by iedwin** [comment]
#### 我重新用vue-cli生成了一个项目，修改了main.js和App.vue；
#### main.js
```
import Vue from 'vue'
import App from './App.vue'

import Element from 'element-ui'
import 'element-ui/lib/theme-default/index.css'

Vue.use(Element)

new Vue({
  el: '#app',
  render: h => h(App)
})
```

#### App.vue:
```
<template>
  <div id="app">
    <el-button>默认按钮</el-button>
   <el-button type="primary">主要按钮</el-button>
    <el-button type="text">文字按钮</el-button>
  </div>
</template>
```
#### 还是会报错，说css无法读取：
```
ERROR in ./~/element-ui/lib/theme-default/index.css
Module parse failed: /Users/fan/Code/Centling/Vue/edwin-vue2/node_modules/element-ui/lib/theme-default/index.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "UTF-8";.el-breadcrumb:after,.el-breadcrumb:before,.el-form-item:after,.el-form-item:before,.el-form-item__content:after,.el-form-item__content:before{display:table;content:""}.el-alert,.el-notification,.el-radio__inner{box-sizing:border-box}.el-radio,.el-radio-button__inner,.el-slider__pop,.el-switch__label{-webkit-user-select:none;-moz-user-select:none}.el-breadcrumb:after,.el-button-group:after,.el-form-item:after,.el-form-item__content:after,.el-menu:after,.el-row:after,.el-tabs__header:after{clear:both}.el-autocomplete__suggestions.is-loading li:after{display:inline-block;content:"";height:100%;vertical-align:middle}.el-button-group:after,.el-button-group:before{display:table;content:""}@font-face{font-family:element-icons;src:url(fonts/element-icons.eot?t=1472440741),url(fonts/element-icons.woff?t=1472440741) format('woff'),url(fonts/element-icons.ttf?t=1472440741) format('truetype'),url(fonts/element-icons.svg?t=1472440741#el-icon) format('svg');font-weight:400;font-style:normal}[class*=" el-icon-"],[clas
```

**Comment by iedwin** [comment]
#### 在webpack.config.js中加入css-loader, 报了另外一个错误：
```
{test: /\.css$/, loader: "style!css"},
```

#### Error:
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'style' in '/Users/fan/Code/Centling/Vue/edwin-vue2'
 @ ./src/main.js 5:0-48
 @ multi main
```

**Comment by furybean** [comment]
@iedwin 感觉是没有安装 style-loader？可以执行一下 `npm i style-loader --save-dev` 试试。

另外，如果对 webpack 用的不是特别熟练的话，可以考虑直接使用 [cooking](http://elemefe.github.io/cooking/) 。

**Comment by iedwin** [comment]
### 问题已解决。

+ 重新使用cooking生成vue2脚手架工程。
+ 在main.js手工导入css;
```
import Vue from 'vue';
import App from './app';
import Element from 'element-ui';
import 'element-ui/lib/theme-default/index.css';

Vue.use(Element);

new Vue({ // eslint-disable-line
  el: '#app',
  render: h => h(App)
});
```
+ tomplate中的元素必须有root element包裹;
```
<template>
  <div>
    <el-button>默认按钮</el-button>
	<el-button type="primary">主要按钮</el-button>
	<el-button type="text">文字按钮</el-button>
  </div>
</template>
```

**Comment by Timson020** [comment]
按照官网的介绍入门，这样的配置真的会报出这样的错误！
import 'element-ui/lib/theme-default/index.css';
就会报出引用不了，解析不了的错误！
建议 团队 尝试一下，是不是还漏了一些配置依赖？
例如其他的loader ？
我使用的是 
vue init webpack-simple [projectName];
npm install element-ui@next --save-dev

**Comment by Leopoldthecoder** [comment]
近期会更新文档，说明一下这个问题。

**Comment by furybean** [comment]
@Timson020 需要贴一下报错信息。

**Comment by Timson020** [comment]
以下就是报错信息
VM1936:1 Uncaught Error: Module parse failed: /Users/Timson/Desktop/CASE/Vue-demo/node_modules/element-ui/lib/theme-default/index.css Unexpected character '@'

**Comment by QingWei-Li** [comment]
@Timson020 FAQ 第四条

**Comment by Timson020** [comment]
@QingWei-Li 
我就是按照quick-start：
上面去配置的 
首先初始化项目
vue init webpack-simple projectName
然后 npm install 安装依赖
然后 npm install element-ui@next --save-dev

最后在main.js 里面
import Element from 'element-ui'

import 'element-ui/lib/theme-default/index.css'

Vue.use(Element)

最后直接npm run dev 就报出错误了

我的步骤应该是没错的
都按照quick-start说的做了
是不是脚手架工具不同，没有对应的loader才导致这样的报错？

**Comment by Timson020** [comment]
@QingWei-Li 
好的  看到了  感谢！
问题已经解决
webpack 2.x 好像不支持loader 这个key了 改成rules  了
