### ISSUE TITLE
[Bug Report]  An error occurred when runs "make new" command

### ISSUE THREAD

**Issue by ljxyweb** [ElemeFE/element#8992]
### Element UI version
2.0.9

### OS/Browsers version
win7

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
"make new xxxx"

### What is Expected?
ok

### What is actually happening?

e:\新建文件夹\element\build\bin\new.js:123
  groups[groups.length - 1].list.push({
               ^

TypeError: Cannot read property 'length' of undefined
    at Object.keys.forEach.lang (e:\新建文件夹\element\build\bin\new.js:123:16)
    at Array.forEach (native)
    at Object.<anonymous> (e:\新建文件夹\element\build\bin\new.js:121:28)
    at Module._compile (module.js:566:14)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

----------------change this --------------
let groups = navConfigFile[lang][3].groups;
----->
let groups = navConfigFile[lang];
groups = groups[groups.length - 1].groups;

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/9000

**Comment by ljxyweb** [comment]
I think it is better to use the array's length than to change 3 to 4
