### ISSUE TITLE
仓库代码下载下来编译报错

### ISSUE THREAD

**Issue by andrewstz** [ElemeFE/element#9645]
下载这个仓库，yarn装好了依赖模块，npm run package.json里script中的任意一条如： npm run build:file都会报错。 不知道啥原因了。  用cnpm i , npm i重装过几次模块都没用。

**Comment by andrewstz** [comment]
Error: Cannot find module 'json-templater/string'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shitianzhu/Documents/study/js/framework/vue/gitlib/element/build/bin/build-entry.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
module.js:529
    throw err;
    ^

Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shitianzhu/Documents/study/js/framework/vue/gitlib/element/build/bin/iconInit.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
