### ISSUE TITLE
[Bug Report] compiled warehouse source code error

### ISSUE THREAD

**Issue by andrewstz** [ElemeFE/element#9646]
### Element UI version
2.1.0

### OS/Browsers version
mac10.11.6

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
下载这个仓库，yarn装好了依赖模块，npm run package.json里script中的任意一条如： npm run build:file都会报错。 不知道啥原因了。 用cnpm i , npm i重装过几次模块都没用。

### What is Expected?
能够编译成功

### What is actually happening?
各种找不到运行文件、库

**Comment by andrewstz** [comment]
npm run build:file
Error: Cannot find module 'json-templater/string'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (element/build/bin/build-entry.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
module.js:529
    throw err;
    ^

Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (element/build/bin/iconInit.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by Leopoldthecoder** [comment]
yarn 确保是最新版本，然后对照 yarn.lock 和 node_modules 看一下吧。
